version: '3.7'

services:
  gzfly:
    restart: always
    image: whatwewant/gzfly:${SERVICE_GZFLY_IMAGE_VERSION}
    ports:
      - 0.0.0.0:8036:8080
    environment:
      DEBUG: 'true'
    volumes:
      - $SERVICE_CONFIGS:/conf
      
networks:
  default:
    external: true
    name: compose-ingress
